version: '3'

services:
  db:
    image: mongo:5
    restart: always
    ports:
      - '${MONGODB_PORT}:27017'
    environment:
      MONGODB_DATABASE: ${MONGODB_DATABASE}
      MONGODB_PORT: ${MONGODB_PORT}
    volumes:
      - ./.db:/data/db
